services:
  doorkeeper_db:
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./data:/var/lib/postgresql/data

  doorkeeper_rails:
    build: ./myapp
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - |
        rails db:create
        rails db:migrate
        rails db:seed
        rm -f tmp/pids/server.pid
        bundle exec rails s -p 2000 -b '0.0.0.0'
    volumes:
      - ./myapp:/home/dev-user/myapp
    ports:
      - "2000:2000"
    depends_on:
      - doorkeeper_db
    # user: dev-user